### ISSUE TITLE
Gerrymandering fairness

### ISSUE THREAD

**Issue by shivashankarrs** [frstyang/fairness-with-overlapping-groups#1]
Thanks for the code repo.

Can you please help me with executing scripts for Gerrymandering group fairness. The instructions in readme seem to cover only independent group fairness.

**Comment by shivashankarrs** [comment]
Running with experiment file gerry_exp.py, with the following config throws error for me, please let me know if this is the right way to execute for gerrymandering fairness.

```
methods = [groupfair.Plugin, groupfair.WERM, gerfair.GerryFair]
params_list = [{'B':[10], 'nu':np.logspace(-4,0,20), 'T':[10000], 'gfair': ['gerry'], 'lr': [1], 'fairness': ['EO'], 'lambda_update': ['subgradient']},
               {'B':[10], 'nu':np.logspace(-4,0,20), 'T':[10000], 'gfair': ['gerry'], 'lr': [1], 'fairness': ['EO'], 'lambda_update': ['subgradient']},
{'C':[15], 'nu':np.logspace(-3,0,20), 'T':[1500]}]
```

**Comment by frstyang** [comment]
Dear Shivashankar,

Thank you for pointing this out. You are right, that file is wrong, 'gerry'
should be gfair not fairness. The fairness should be DP. I modified the
config file on github and added instructions to the readme, take another
look and let me know if anything goes wrong.

Best,
Forest

**Comment by shivashankarrs** [comment]
Thanks a lot for the quick response Forest. For groupfair.WERM, the weights are not initialized for 'gerry'.

```
weights = weights - weights.min(axis=1)[:, None]
UnboundLocalError: local variable 'weights' referenced before assignment
```

Also, can the `plugin` approach be extended for 'EO' by changing the vector suitably? (`cost = cost + viol_weights[:, None]*np.array([0,0,0,1])`)

**Comment by shivashankarrs** [comment]
Or can I just pre-compute gerry groups for each dataset, and use it with `ind` experiments.

**Comment by frstyang** [comment]
Dear Shivashankar,

I have also fixed this, thanks for pointing out weights not being initialized. The difference between 'gerry' and 'ind' as observed by the groupfair algorithm is simply a matter of scaling by the group size (gerrymandering fairness scales by group size, independent fairness does not). You can still precompute the gerrymandering groups with the utils.int_gerry function and use 'ind', it would simply not scale violations by group size (which would return an extremely difficult problem due to the number of very small groups in that case).

**Comment by shivashankarrs** [comment]
Thanks Forest :) The code works fine for me now.

I have a general query --- when we use inverse of probability of a group as a weight in the loss function (equation 2 in the paper, page 5 https://arxiv.org/pdf/2006.13485.pdf), is the idea to weigh the smaller groups higher (group specific weights)? analogous to class imbalance learning where rare classes are weighted more (class specific weights).

**Comment by frstyang** [comment]
Yeah, that seems a valid way of interpreting the inverse probability
weighting. There’s a derivation of it in the paper, it comes from writing
the conditional expectation using indicator/probability factor.

**Comment by shivashankarrs** [comment]
Thanks Forest. For evaluation on test data, is the max violation metric weighted or unweighted by the size of population?

**Comment by frstyang** [comment]
Sorry for the late reply, Shivashankar. Good question. For the gerry
experiments, the violation measure (that is used during test time) is
calc_gerry_viol, which weights by group size. You can see this because its
return value (utils.py, line 87) is (sum of predictions in group)/n -
(global avg prediction)*(group prob) = (group size)/n * ( (sum of
predictions in group) / group_size - (global avg prediction)) = (group
prob) * (violation). In the gerry_exp experiment file, gfair is also set to
gerry, which makes the GroupFair algorithm also weight by group size (see
calc_viol method of GroupFair algorithm). For non-gerry experiments, max
violation is used.

**Comment by shivashankarrs** [comment]
Thanks Forest :)
